swagger: "2.0"
info:
  title: "Game evidence system"
  version: "0.1"
  description: "Game evidence system"
  contact:
    email: "jtomekcz@google.com"
host: "localhost"
basePath: "/"

tags:
- name: "gameevidence"
  description: "evidence of players and their teams"

schemes:
- "http"

paths:

  /all-players:
    get:
      summary: gets all active players
      tags:
      - gameevidence
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/PlayersList"
        400:
          description: Bad Request
        500:
          description: Internal Server error - tech. chyba

##----------------------------------------------------
definitions:
  ##--
  Player:
    type: object
    properties:
      alias:
        type: string
        description: alias of given player
      winnersCount:
        type: integer
        format: int32
        description: count of players winners
      lostsCount:
        type: integer
        format: int32
        description: count of players losts

  ##--
  Team:
    type: object
    properties:
      alias:
        type: string
        description: alias of given team
      winnersCount:
        type: integer
        format: int32
        description: count of players winners
      lostsCount:
        type: integer
        format: int32
        description: count of players losts
      maxPlayersCount:
        type: integer
        format: int32
        description: maximum count of players in given team
      players:
        $ref: "#/definitions/PlayersList"


  ##--
  Game:
    type: object
    properties:
      alias:
        type: string
        description: alias of given team
      winnersCount:
        type: integer
        format: int32
        description: count of players winners
      lostsCount:
        type: integer
        format: int32
        description: count of players losts

  ##--
  PlayersList:
    type: array
    items:
      $ref: '#/definitions/Player'
